baseurl = "/"
languagecode = "en-us"

# This website is primarity in chinese, set this optio to ture  will be make 
# hugo summary and word count work better.
hasCJKLanguage = true
# ignore files created in rstudio
ignoreFiles =["\\.Rmd", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
theme = "hugo-hatw"

[Languages.en]
  title="Choyang"
[Languages.zh]
  title = "一路嘿嘿"


##---------- languages en and zh ----------------##
defaultContentLanguage = "en"
# Force the content of default language in subdir, e.g. `content/en/`. The site 
# root `/` will then redirect to `/en/`.
defaultContentLanguageInSubdir = true

# zh
[[Languages.zh.menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[Languages.zh.menu.main]]
    name = "关于"
    url = "/zh/about/"
    weight = 2
[[Languages.zh.menu.main]]
    name = "存档"
    url = "/zh/post/"
    weight = 3
[params]
  bio = "Bioinformatics, R enthusiast. Thoughts on reasarch, personal experience and other distractions."
  copyright = "&copy; 2018 Choyang Powered by [Hugo](http://gohugo.io/) and [blogdown](https://github.com/yihui/blogdown)"
  bootswatch = "lux"
  [params.navbar]
      color = "navbar-light"
      bg_color = "bg-light"
    
    # social network
    [[params.social]]
      icon = "github"
      icon_pack = "fa"
      link = "//github.com/yiluheihei"
    
    [[params.social]]
      icon = "envelope"
      icon_pack = "fa"
      link = "mailto:yiluheihei@gmail.com"